apiVersion: v1
kind: Secret
metadata:
  name: repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: kubernetes.io/basic-auth
stringData:
  username: sachin857
  password: sasasas
